### ISSUE TITLE
Add indexing of datacite for ATX DOIs

### ISSUE THREAD

**Issue by tom-montgomery** [cityofaustin/doi-automation#8]
we need to index datacite for DOIs programmatically in case someone manually adds a DOI. This is because the doi_assets table suffixes need to be up to date for the DOI assignment to work.

**Comment by tom-montgomery** [comment]
'https://api.datacite.org/clients/AUSTINTX.ATXDR/dois' gives 25 results,  even though we have 31 DOIs. needs investigation

**Comment by mateoclarke** [comment]
When we check the Datacite API for existing records in extract_metadata.py, we need to check those records against those we created in doi_assets.json. If records from Datacite don't exist yet in the doi_assets.json file, they were manually created and we need to update the json include all the fields. xml is the most important, encoded with base64

**Comment by tom-montgomery** [comment]
done
